### ISSUE TITLE
Build instructions are missing freetype2 and freeglut dependencies

### ISSUE THREAD

**Issue by str4d** [FoldingAtHome/fah-viewer#13]
I'm attempting to build `fah-viewer` on Windows 10. Once I worked around CauldronDevelopmentLLC/cbang#44 and #12, I discovered that there were undocumented dependencies on `freetype2` and `freeglut`. I was able to find a pre-compiled library for the former that appear to work, but I have been thus far unable to find or build a `freeglut` library that will work with `fah-viewer`. It would be very helpful if the `README` documented how to obtain suitable versions of these dependencies.

**Comment by jcoffland** [comment]
I used ``freeglut-3.0.0-4`` from msys2.  http://mirrors.ustc.edu.cn/msys2/mingw/i686/mingw-w64-i686-freeglut-3.0.0-4-any.pkg.tar.xz  You may need the 64-bit version.
